Repository Unity-Technologies/com.unity.search.extensions, pull requests merged in 2021-11, with the labels that each got.

#13 Add ProjectSettings dependencies
  CHANGELOG.md
  Editor/Collections/SearchCollectionOverlay.cs
  Editor/Dependencies/Dependency.cs
  Editor/Dependencies/DependencyIndexer.cs
  TestProject~/ProjectSettings/ProjectSettings.asset
Labels: enhancement

#14 Fix zoom and pan
  CHANGELOG.md
  Editor/Dependencies/Graph/DependencyGraphViewer.cs
Labels: bug, enhancement

#16 Dependency graph viewer column layout
  Editor/Dependencies/Graph/DependencyColumnLayout.cs
  Editor/Dependencies/Graph/DependencyDatabase.cs
  Editor/Dependencies/Graph/DependencyGraph.cs
  Editor/Dependencies/Graph/DependencyGraphUtils.cs
  Editor/Dependencies/Graph/DependencyGraphUtils.cs.meta
  Editor/Dependencies/Graph/DependencyGraphViewer.cs
  Editor/Dependencies/Graph/DependencyUtilities.cs
  Editor/Dependencies/Graph/ForceDirectedLayout.cs
  Editor/Dependencies/Graph/IGraphLayout.cs
  Editor/Dependencies/Graph/OrganicLayout.cs
  TestProject~/Assets/Editor/ColumnLayoutTests.cs
  TestProject~/Assets/Editor/ColumnLayoutTests.cs.meta
  TestProject~/Assets/Editor/com.unity.search.extensions.tests.asmdef
  TestProject~/Assets/Resources.meta
  TestProject~/Assets/Resources/BillingMode.json
  TestProject~/Assets/Resources/BillingMode.json.meta
Labels: enhancement

#20 Add test project for 20.3 with com.unity.quicksearch@3.0.0-preview.22
  .yamato/upm-ci.yml
  Editor/Dependencies/Dependency.cs
  Editor/Dependencies/DependencyTableView.cs
  Editor/Dependencies/DependencyViewer.cs
  Editor/Dependencies/Graph/DependencyColumnLayout.cs
  Editor/Dependencies/Graph/DependencyGraph.cs
  Editor/Dependencies/Graph/DependencyGraphUtils.cs
  Editor/Dependencies/Graph/DependencyGraphViewer.cs
  Editor/Dependencies/Graph/ForceDirectedLayout.cs
  Editor/Dependencies/Graph/IGraphLayout.cs
  Editor/Dependencies/Graph/OrganicLayout.cs
  Editor/Selectors/CustomSelectors.cs
  TestProject~/ProjectSettings/ProjectSettings.asset
  Tests.meta
  Tests/Dependencies~/.gitattributes
  Tests/Dependencies~/.gitignore
  Tests/Dependencies~/Assets/Editor.meta
  Tests/Dependencies~/Assets/Editor/ColumnLayoutTests.cs
  Tests/Dependencies~/Assets/Editor/ColumnLayoutTests.cs.meta
  Tests/Dependencies~/Assets/Editor/DependencyProviderTests.cs
  Tests/Dependencies~/Assets/Editor/DependencyProviderTests.cs.meta
  Tests/Dependencies~/Assets/Editor/TestUtils.cs
  Tests/Dependencies~/Assets/Editor/TestUtils.cs.meta
  Tests/Dependencies~/Assets/Editor/com.unity.search.extensions.tests.asmdef
  Tests/Dependencies~/Assets/Editor/com.unity.search.extensions.tests.asmdef.meta
  Tests/Dependencies~/Assets/Materials.meta
  Tests/Dependencies~/Assets/Materials/Red.mat
  Tests/Dependencies~/Assets/Materials/Red.mat.meta
  Tests/Dependencies~/Assets/Prefabs.meta
  Tests/Dependencies~/Assets/Prefabs/Simple.prefab
  Tests/Dependencies~/Assets/Prefabs/Simple.prefab.meta
  Tests/Dependencies~/Assets/Resources.meta
  Tests/Dependencies~/Assets/Resources/BillingMode.json
  Tests/Dependencies~/Assets/Resources/BillingMode.json.meta
  Tests/Dependencies~/Assets/Runtime.meta
  Tests/Dependencies~/Assets/Runtime/ManyRefs.asset
  Tests/Dependencies~/Assets/Runtime/ManyRefs.asset.meta
  Tests/Dependencies~/Assets/Scripts.meta
  Tests/Dependencies~/Assets/Scripts/ManyRefs.cs
  Tests/Dependencies~/Assets/Scripts/ManyRefs.cs.meta
  Tests/Dependencies~/Assets/Scripts/ToScriptableObject.cs
  Tests/Dependencies~/Assets/Scripts/ToScriptableObject.cs.meta
  Tests/Dependencies~/Packages/manifest.json
  Tests/Dependencies~/Packages/packages-lock.json
  Tests/com.unity.quicksearch~/.gitattributes
  Tests/com.unity.quicksearch~/.gitignore
  Tests/com.unity.quicksearch~/Assets/Editor.meta
  Tests/com.unity.quicksearch~/Assets/Editor/DependencyViewerTests.cs
  Tests/com.unity.quicksearch~/Assets/Editor/DependencyViewerTests.cs.meta
  Tests/com.unity.quicksearch~/Assets/Editor/com.unity.search.extensions.tests.asmdef
  Tests/com.unity.quicksearch~/Assets/Editor/com.unity.search.extensions.tests.asmdef.meta
  Tests/com.unity.quicksearch~/Packages/manifest.json
  Tests/com.unity.quicksearch~/Packages/packages-lock.json
Labels: tests

#19 Use borderless search view flag
  Editor/Dependencies/Graph/DependencyGraphViewer.cs
Labels: bug, tests
